// Seed data for a realistic Japanese examination platform demo.
// All passwords are "password123" (hash placeholder). In production these would
// be bcrypt-hashed server-side.

import type { Exam, Question, User } from "./types";

export const seedUsers: (User & { plainPassword: string })[] = [
  {
    id: "u_admin_1",
    email: "admin@jexam.jp",
    passwordHash: "sim$password123",
    plainPassword: "password123",
    fullName: "Yuki Tanaka",
    fullNameJa: "田中 由紀",
    role: "admin",
    createdAt: "2025-01-05T09:00:00Z",
  },
  {
    id: "u_inv_1",
    email: "invigilator@jexam.jp",
    passwordHash: "sim$password123",
    plainPassword: "password123",
    fullName: "Hiroshi Sato",
    fullNameJa: "佐藤 寛",
    role: "invigilator",
    createdAt: "2025-01-05T09:05:00Z",
  },
  // Candidates - the demo seeds 36 so we exceed the 30-concurrent requirement.
  ...Array.from({ length: 36 }).map((_, i) => {
    const n = (i + 1).toString().padStart(3, "0");
    const families = [
      "Sato",
      "Suzuki",
      "Takahashi",
      "Tanaka",
      "Watanabe",
      "Ito",
      "Yamamoto",
      "Nakamura",
      "Kobayashi",
      "Kato",
      "Yoshida",
      "Yamada",
      "Sasaki",
      "Yamaguchi",
      "Matsumoto",
      "Inoue",
      "Kimura",
      "Shimizu",
      "Hayashi",
      "Saito",
    ];
    const givens = [
      "Haruto",
      "Yuto",
      "Sota",
      "Yuki",
      "Hina",
      "Aoi",
      "Ren",
      "Kaito",
      "Sakura",
      "Mei",
      "Riko",
      "Hiroto",
      "Akari",
      "Minato",
      "Tsubasa",
      "Kokoro",
      "Itsuki",
      "Rin",
      "Kana",
      "Sora",
    ];
    const f = families[i % families.length];
    const g = givens[(i * 3) % givens.length];
    return {
      id: `u_cand_${n}`,
      email: `candidate${n}@jexam.jp`,
      passwordHash: "sim$password123",
      plainPassword: "password123",
      fullName: `${g} ${f}`,
      fullNameJa: `${f} ${g}`,
      registrationNumber: `JLPT-2025-${n}`,
      role: "candidate" as const,
      createdAt: "2025-01-10T10:00:00Z",
    };
  }),
];

// JLPT N5 style sample questions - one exam, mixed question types.
const examId = "exam_n5_2025_spring";

const questions: Question[] = [
  // ===== Vocabulary (文字・語彙) =====
  {
    id: "q_vocab_1",
    examId,
    type: "vocabulary",
    section: "文字・語彙",
    level: "N5",
    prompt:
      "Choose the correct reading of the underlined word: 学校の前に友達がいます。",
    promptJa: "学校の前に友達がいます。",
    choices: [
      { id: "a", text: "がっこう", textJa: "がっこう" },
      { id: "b", text: "がくこう", textJa: "がくこう" },
      { id: "c", text: "がっこ", textJa: "がっこ" },
      { id: "d", text: "がくこ", textJa: "がくこ" },
    ],
    correctAnswer: "a",
    points: 1,
    explanation: "学校 is read as がっこう.",
  },
  {
    id: "q_vocab_2",
    examId,
    type: "vocabulary",
    section: "文字・語彙",
    level: "N5",
    prompt: "What is the meaning of 美しい?",
    promptJa: "美しい",
    choices: [
      { id: "a", text: "expensive" },
      { id: "b", text: "beautiful" },
      { id: "c", text: "busy" },
      { id: "d", text: "boring" },
    ],
    correctAnswer: "b",
    points: 1,
  },
  {
    id: "q_vocab_3",
    examId,
    type: "vocabulary",
    section: "文字・語彙",
    level: "N5",
    prompt: 'Choose the correct kanji for "mizu" (water).',
    choices: [
      { id: "a", text: "水" },
      { id: "b", text: "木" },
      { id: "c", text: "火" },
      { id: "d", text: "土" },
    ],
    correctAnswer: "a",
    points: 1,
  },
  {
    id: "q_vocab_4",
    examId,
    type: "vocabulary",
    section: "文字・語彙",
    level: "N5",
    prompt: "Choose the word that best fits: 毎朝、コーヒーを____飲みます。",
    choices: [
      { id: "a", text: "のぼる" },
      { id: "b", text: "のむ" },
      { id: "c", text: "ねる" },
      { id: "d", text: "なく" },
    ],
    correctAnswer: "b",
    points: 1,
  },
  {
    id: "q_vocab_5",
    examId,
    type: "vocabulary",
    section: "文字・語彙",
    level: "N5",
    prompt: "What does 今日 mean?",
    choices: [
      { id: "a", text: "yesterday" },
      { id: "b", text: "tomorrow" },
      { id: "c", text: "today" },
      { id: "d", text: "now" },
    ],
    correctAnswer: "c",
    points: 1,
  },

  // ===== Kanji =====
  {
    id: "q_kanji_1",
    examId,
    type: "kanji",
    section: "文字・語彙",
    level: "N5",
    prompt: "Read this kanji: 山",
    choices: [
      { id: "a", text: "かわ" },
      { id: "b", text: "やま" },
      { id: "c", text: "うみ" },
      { id: "d", text: "そら" },
    ],
    correctAnswer: "b",
    points: 1,
  },
  {
    id: "q_kanji_2",
    examId,
    type: "kanji",
    section: "文字・語彙",
    level: "N5",
    prompt: 'How do you write "tabemono" in kanji?',
    choices: [
      { id: "a", text: "飲物" },
      { id: "b", text: "食べ物" },
      { id: "c", text: "動物" },
      { id: "d", text: "読物" },
    ],
    correctAnswer: "b",
    points: 1,
  },
  {
    id: "q_kanji_3",
    examId,
    type: "kanji",
    section: "文字・語彙",
    level: "N5",
    prompt: 'Which kanji means "person"?',
    choices: [
      { id: "a", text: "人" },
      { id: "b", text: "入" },
      { id: "c", text: "八" },
      { id: "d", text: "刀" },
    ],
    correctAnswer: "a",
    points: 1,
  },

  // ===== Grammar (文法) =====
  {
    id: "q_gram_1",
    examId,
    type: "grammar",
    section: "文法",
    level: "N5",
    prompt: "Fill in the blank: 私は毎日日本____勉強します。",
    choices: [
      { id: "a", text: "が" },
      { id: "b", text: "を" },
      { id: "c", text: "に" },
      { id: "d", text: "で" },
    ],
    correctAnswer: "b",
    points: 1,
    explanation: "を marks the direct object of a transitive verb.",
  },
  {
    id: "q_gram_2",
    examId,
    type: "grammar",
    section: "文法",
    level: "N5",
    prompt: "Choose the correct particle: 駅____歩いて行きます。",
    choices: [
      { id: "a", text: "まで" },
      { id: "b", text: "から" },
      { id: "c", text: "に" },
      { id: "d", text: "と" },
    ],
    correctAnswer: "a",
    points: 1,
  },
  {
    id: "q_gram_3",
    examId,
    type: "grammar",
    section: "文法",
    level: "N5",
    prompt: "Select the correct form: 私は学生____。",
    choices: [
      { id: "a", text: "です" },
      { id: "b", text: "でした" },
      { id: "c", text: "でしょう" },
      { id: "d", text: "だろう" },
    ],
    correctAnswer: "a",
    points: 1,
  },
  {
    id: "q_gram_4",
    examId,
    type: "grammar",
    section: "文法",
    level: "N5",
    prompt: "Choose the most natural sentence.",
    choices: [
      { id: "a", text: "私は毎朝コーヒーを飲みます。" },
      { id: "b", text: "私は毎朝コーヒーが飲みます。" },
      { id: "c", text: "私は毎朝コーヒーには飲みます。" },
      { id: "d", text: "私は毎朝コーヒーまで飲みます。" },
    ],
    correctAnswer: "a",
    points: 1,
  },

  // ===== MCQ (general) =====
  {
    id: "q_mcq_1",
    examId,
    type: "mcq",
    section: "読解",
    level: "N5",
    prompt: 'Which is a polite way to say "good morning"?',
    choices: [
      { id: "a", text: "おはよう" },
      { id: "b", text: "おはようございます" },
      { id: "c", text: "こんにちは" },
      { id: "d", text: "こんばんは" },
    ],
    correctAnswer: "b",
    points: 1,
  },
  {
    id: "q_mcq_2",
    examId,
    type: "mcq",
    section: "読解",
    level: "N5",
    prompt: "What number is 百?",
    choices: [
      { id: "a", text: "10" },
      { id: "b", text: "100" },
      { id: "c", text: "1000" },
      { id: "d", text: "10000" },
    ],
    correctAnswer: "b",
    points: 1,
  },

  // ===== Reading Comprehension =====
  {
    id: "q_read_1",
    examId,
    type: "reading",
    section: "読解",
    level: "N5",
    prompt:
      "Read the passage and answer the question.\n\nメアリーさんは毎朝七時に起きます。それから、シャワーを浴びて、朝ごはんを食べます。食べたら、歯を磨いて、家を出ます。会社まで電車で三十分かかります。会社はとても忙しいですが、メアリーさんは仕事が大好きです。",
    readingPassage:
      "メアリーさんは毎朝七時に起きます。それから、シャワーを浴びて、朝ごはんを食べます。食べたら、歯を磨いて、家を出ます。会社まで電車で三十分かかります。会社はとても忙しいですが、メアリーさんは仕事が大好きです。",
    promptJa: "メアリーさんは毎朝何時に起きますか。",
    choices: [
      { id: "a", text: "6時" },
      { id: "b", text: "7時" },
      { id: "c", text: "8時" },
      { id: "d", text: "9時" },
    ],
    correctAnswer: "b",
    points: 2,
  },
  {
    id: "q_read_2",
    examId,
    type: "reading",
    section: "読解",
    level: "N5",
    prompt: "How does Mary get to work?",
    readingPassage:
      "メアリーさんは毎朝七時に起きます。それから、シャワーを浴びて、朝ごはんを食べます。食べたら、歯を磨いて、家を出ます。会社まで電車で三十分かかります。",
    choices: [
      { id: "a", text: "by bus" },
      { id: "b", text: "by train" },
      { id: "c", text: "by car" },
      { id: "d", text: "on foot" },
    ],
    correctAnswer: "b",
    points: 2,
  },
  {
    id: "q_read_3",
    examId,
    type: "reading",
    section: "読解",
    level: "N5",
    prompt: "How long does it take Mary to get to work?",
    readingPassage:
      "会社まで電車で三十分かかります。会社はとても忙しいですが、メアリーさんは仕事が大好きです。",
    choices: [
      { id: "a", text: "10 minutes" },
      { id: "b", text: "20 minutes" },
      { id: "c", text: "30 minutes" },
      { id: "d", text: "60 minutes" },
    ],
    correctAnswer: "c",
    points: 2,
  },

  // ===== Listening Comprehension (simulated; in this demo, plays no real audio) =====
  {
    id: "q_list_1",
    examId,
    type: "listening",
    section: "聴解",
    level: "N5",
    prompt:
      "[Audio] 田中さん: 「すみません、駅はどこですか。」 女性: 「この道をまっすぐ行って、右側にあります。」 Where is the station?",
    audioUrl: "/mock-audio/list-1.mp3",
    choices: [
      { id: "a", text: "On the left" },
      { id: "b", text: "On the right" },
      { id: "c", text: "Behind us" },
      { id: "d", text: "In front" },
    ],
    correctAnswer: "b",
    points: 2,
  },
  {
    id: "q_list_2",
    examId,
    type: "listening",
    section: "聴解",
    level: "N5",
    prompt:
      "[Audio] 男性: 「いま、何時ですか。」 女性: 「三時十五分です。」 What time is it?",
    audioUrl: "/mock-audio/list-2.mp3",
    choices: [
      { id: "a", text: "2:15" },
      { id: "b", text: "3:15" },
      { id: "c", text: "3:50" },
      { id: "d", text: "4:15" },
    ],
    correctAnswer: "b",
    points: 2,
  },
  {
    id: "q_list_3",
    examId,
    type: "listening",
    section: "聴解",
    level: "N5",
    prompt:
      "[Audio] 店員: 「いらっしゃいませ。」 客: 「ラーメンを一つお願いします。」 What does the customer order?",
    audioUrl: "/mock-audio/list-3.mp3",
    choices: [
      { id: "a", text: "sushi" },
      { id: "b", text: "ramen" },
      { id: "c", text: "curry" },
      { id: "d", text: "udon" },
    ],
    correctAnswer: "b",
    points: 2,
  },
];

export const seedQuestions: Question[] = questions;

export const seedExams: Exam[] = [
  {
    id: examId,
    title: "JLPT N5 Spring 2025 Mock Examination",
    titleJa: "日本語能力試験 N5 模擬試験 (2025年春)",
    level: "N5",
    description:
      "A complete JLPT-style N5 mock examination covering vocabulary, kanji, grammar, reading comprehension, and listening comprehension. 20 questions, 45 minutes.",
    durationMinutes: 45,
    startWindowStart: "2025-03-15T00:00:00Z",
    startWindowEnd: "2025-12-31T23:59:59Z",
    totalPoints: questions.reduce((s, q) => s + q.points, 0),
    passingScore: Math.ceil(questions.reduce((s, q) => s + q.points, 0) * 0.6),
    questionIds: questions.map((q) => q.id),
    antiCheating: {
      enforceFullscreen: true,
      blockCopyPaste: true,
      blockRightClick: true,
      blockDevTools: true,
      allowTabSwitch: true,
      maxTabSwitches: 3,
      maxFullscreenExits: 2,
      maxCopyPasteAttempts: 2,
      detectWebsites: true,
      requireWebcam: false,
      recordScreen: false,
    },
    assignedCandidateIds: seedUsers
      .filter((u) => u.role === "candidate")
      .map((u) => u.id),
    status: "live",
    createdAt: "2025-02-01T00:00:00Z",
  },
  {
    id: "exam_n4_2025_summer",
    title: "JLPT N4 Summer 2025 Practice Test",
    titleJa: "日本語能力試験 N4 練習問題 (2025年夏)",
    level: "N4",
    description: "Practice test for N4 level. Not yet started.",
    durationMinutes: 60,
    startWindowStart: "2025-07-01T00:00:00Z",
    startWindowEnd: "2025-08-31T23:59:59Z",
    totalPoints: 0,
    passingScore: 0,
    questionIds: [],
    antiCheating: {
      enforceFullscreen: true,
      blockCopyPaste: true,
      blockRightClick: true,
      blockDevTools: true,
      allowTabSwitch: true,
      maxTabSwitches: 3,
      maxFullscreenExits: 2,
      maxCopyPasteAttempts: 2,
      detectWebsites: true,
      requireWebcam: false,
      recordScreen: false,
    },
    assignedCandidateIds: [],
    status: "scheduled",
    createdAt: "2025-02-15T00:00:00Z",
  },
];
