import { NextRequest, NextResponse } from "next/server";
import { execFile } from "child_process";
import { promisify } from "util";
import { getWorkspaceRoot, ensureWorkspace } from "@/lib/workspace";

const execFileAsync = promisify(execFile);

export const runtime = "nodejs";

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const projectId = searchParams.get("projectId") || "default";

    await ensureWorkspace(projectId);
    const root = getWorkspaceRoot(projectId);

    // Get git commits in format: sha|timestamp|message
    // Using %H for full hash, %at for author date timestamp, %s for subject
    const { stdout } = await execFileAsync(
      "git",
      ["log", "--max-count=30", "--format=%H|%at|%s"],
      { cwd: root }
    ).catch(() => ({ stdout: "" }));

    const checkpoints = stdout
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        const [sha, timestamp, message] = line.split("|");
        return {
          sha,
          timestamp: parseInt(timestamp, 10) * 1000,
          message: message || "Checkpoint",
        };
      })
      // Only return checkpoints generated by the agent or initial commit
      .filter((c) => c.message.includes("checkpoint:") || c.message.includes("initial"));

    return NextResponse.json({ success: true, checkpoints });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : String(err) },
      { status: 500 }
    );
  }
}
